atom/language-php

grammars/php.cson
This properly identifies "finally" as an exception keyword instead of a constant.
=> Properly identify finally keyword

snippets/language-php.cson
While not required in the scenario of html/php, ending semicolons make it easier to add new code within existing PHP tags. I had thought that some coding standards mandated this, but I didn't find a supporting case so there is that caveat. Thanks for taking a look.
=> Adding semicolons after control structures in .text.html.

grammars/php.cson, spec/php-spec.coffee
This pull request will fix https://github.com/atom/language-php/issues/29
=> Fixed so namespaces syntax works on same lime as <?php

grammars/php.cson, package.json, spec/php-spec.coffee
This pull request will fix https://github.com/atom/language-php/issues/64
=> Fixed default short array value syntax error

grammars/php.cson, spec/php-spec.coffee
Added syntax support for `@api` 
See http://phpdoc.org/docs/latest/references/phpdoc/tags/api.html or https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#81-api
=> Added syntax support for PHPDoc api tag

grammars/php.cson, spec/php-spec.coffee
Noted that this PHPDoc tags was missing from the syntax highlighting. This pull request will add support for the missing tags.
Reference: http://phpdoc.org/docs/latest/references/phpdoc/tags/
* `@method`
* `@property`
* `@property-read`
* `@property-write`
* `@source`
=> Added support for phpdoc method, property and source tags

settings/language-php.cson
Refs #63 
Previously, a `]` needed to be followed by a `,` or a `;` to trigger an outdent. I've now included plain `]` at the end of the line in the pattern by changing the pattern from `\][,;]` to `\]([,;]]|$)`.
These multi-line indent/outdent regexes were converted from the TextMate bundle and look horrific, but I just left them this way and made a small edit.
It would be great if someone could test out this branch for a while and make sure there's no unintended consequences. I'm not experienced in PHP at all.
/cc @JesseLeite @crantok
=> Include ] at end of line in outdent pattern

snippets/language-php.cson
- Create new line after brackets (as PSR-2 recomments)
- Add visibility to the method (`public` as default)
- Add type to the first argument
- Define a property name as the same of the first argument
***
The snippet should create something like:
```php
public function __construct(Type $foo = null)
{
$this->foo = $foo;
}
```
=> Improve "function __construct" snippet

grammars/php.cson, spec/php-spec.coffee
`===` is currently being treated as three assignment operators.
=> Fix assignment operator consuming comparison operators

grammars/php.cson
Callable is now considered a type hint, just like array. It now gets storage.type.php instead of support.class.php
Fix for issue #108
=> Changed grammar to include callable as type hint

snippets/language-php.cson
=> Fix doc_f snippet's return type selection

snippets/language-php.cson
The reason for this is exactly the same as for #146. Now all snippets should be fine in terms of their intended scope.
=> Move doc_f snippet to appropriate scope

settings/language-php.cson
Refs #63 
1. A `(` did not trigger an indent except for `array(`
2. A `) {` did not trigger an outdent
=> indent all lines between parentheses

grammars/php.cson, spec/php-spec.coffee
Aside from adding support for Emacs and Vim-style modelines, this PR also fixes a bug with matching interpreter directives, where `#!/usr/local/php/bin` or `#!/bin/$php` would also be matched incorrectly.
=> Add firstLineMatch support for hashbangs/modelines

snippets/language-php.cson
Added php shorthand echo snippet
I do not see any alternate designs
Time saver as shorthand echo is commonly used nowdays and supported since PHP 5.4
I do not see any drawbacks
None.
=> Add Shorthand echo

grammars/php.cson, spec/php-spec.coffee
highlight inline phpdoc correctly
```php
/** @var string Variable */
```
We might want to also support single line comments https://github.com/atom/language-php/issues/135#issuecomment-270901684
highlight inline phpdoc correctly
none
#135
=> Inline phpdoc

grammars/php.cson, spec/php-spec.coffee
Add `JS` as a synonym for `JAVASCRIPT` to tokenize javascript in heredocs and nowdocs
```php
$a = <<<JS
```
would be the same as
```php
$a = <<<JAVASCRIPT
```
More terse. Easier for people to remember.
None
None
=> add JS as a synonym for JAVASCRIPT heredocs

grammars/php.cson
Support the phpdoc keyword `@inheritDoc`
It looked the best to me, and I looked after other things had been implemented.
`@inheritDoc` will be marked as a keyword, so the code will be displayed better.
I don't know any.
Did I need to create one?
=> support @inheritdoc

grammars/php.cson, spec/php-spec.coffee
According to http://php.net/manual/en/functions.user-defined.php function name can contains other characters than letters or numbers
Atom can now highlight function name in php containing for example non breaking space:
```php
function foo bar() {}
```
None
None
=> Fix function name highlight

spec/php-spec.coffee
Most of the specs were incorrectly grouped under the `operators -> combined operators` describe.  Unindent them to provide better context when they fail.
None.
See description.
None.
None.
=> Move most specs out of the 'operators' section

grammars/php.cson, spec/php-spec.coffee
Minimally invasive change to tokenize `$this` as `variable.language.this.php` rather than `variable.other.php`.
None.
Accuracy.
None?
Fixes #34, the last surviving issue for the `variable.language.this` update.
=> Tokenize $this as variable.language.this.php

grammars/php.cson, spec/php-spec.coffee
There's a comment referencing something called "select scope", but I'm pretty sure that doesn't exist in Atom...
None.
PHP strings will be consistent with pretty much every other language out there.
None, unless there is a mysterious "select scope" feature in Atom somewhere?
Fixes https://github.com/atom/language-php/issues/37#issue-44173204
=> Remove meta scope that doesn't exist in any other language

grammars/php.cson
Simple change to add `AND` as a valid SQL keyword to start a string with.
None.
SQL strings starting with `AND` should be properly highlighted as...SQL strings, rather than regular strings.
I foresee some possible issue with someone who _just happens_ to write a regular string that starts with `AND`, maybe "AND...that's the end".  Of course, the same argument is applicable for all the other SQL keywords as well, so I don't think it's that big of a deal.
Fixes #52
=> Add AND as a valid SQL keyword

grammars/php.cson, spec/php-spec.coffee
Adds `punctuation.definition.*.begin/end.bracket.round.php` scopes to all parentheses.  While doing this I uncovered a few bugs and fixed those along the way.  Notably, function and method calls now receive the `entity.name.function.php` scope, catch statements receive proper classes when there is no space between the `catch` and the opening parentheses, and the scope resolution operator now works as expected, rather than always being tokenized as a goto label.  Specs have been added for most/all of the code I touched.
None.
If your syntax theme …
=> Tokenize parentheses

snippets/language-php.cson
Attempts to simultaneously satisfy #76 and #90.  I'm not too happy with this solution, but accept it because it's been there for two years already and the default ac+ confirm keybinding includes enter.
:fire: the new snippet and only change the old one.  On default installations, this will result in `<?<?php` when trying to press enter after `<?php`.
Please everyone?
None.
Fixes #76
Fixes #90
=> Add another PHP snippet

grammars/php.cson, spec/php-spec.coffee
Simple change to add `?>` to the list of valid end patterns when including a PHP file.
None.
`<?php include 'test'?>` syntax will now be properly highlighted.
None.
Fixes #154
=> Fix inline include not stopping at the closing PHP tag

grammars/php.cson, spec/php-spec.coffee
Supports PHP 7.1+ syntax of allowing multiple exception classes in a single catch block.
None.
Keeping up to date with PHP.
None.
Fixes #190
=> Tokenize multiple exceptions in a catch clause

grammars/php.cson, spec/php-spec.coffee
Allow typehinted arguments to have any default value they desire, rather than just `null`.  In addition:
* Restructure the typehint regex to make it cleaner
* Add `keyword.operator.variadic.php` scope to `...`
* Rename `argument` to `parameter` to be consistent with other languages and highlight the difference between function _arguments_ (function calls) and function _parameters_ (functions)
* Recognize function names with capitalized letters (regression from #203)
None
See above.
There may be other bugs related to function parameters.  I'll tackle those …
=> Tokenize typehinted function arguments with default values

grammars/php.cson, spec/php-spec.coffee
Consistently tokenize function return values as `storage.type.php`.
None.
Return types will be tokenized correctly.
None.
Fixes #197 to an extent - the scopes are still different, but I don't think they should be the same in the first place.
=> Tokenize function return values

grammars/php.cson, spec/php-spec.coffee
Wanted to make sure we get some basic specs in for #187.  Comments also have punctuation scopes now.
None.
Protect against regressions, make comments appear identical to the SQL version.
None.
Refs #187
=> Add basic specs for embedded SQL

grammars/php.cson, spec/php-spec.coffee
Adds support for the `use` directive in classes.  In order to differentiate this from the existing `use` namespace syntax, I had to extend the class begin/end to cover the entire class, similar to what Java does.
/cc @jens1o, @Ingramz, @UziTech - any comments on my scope naming?  Anything that I missed?  Mostly I just made sure that the examples at http://php.net/manual/en/language.oop5.traits.php all worked.
None.
First off, the obvious benefit: trait use syntax will be tokenized correctly.  Next, the not-so-obvious benefit: the class regex will be …
=> Support 'use' in traits

grammars/php.cson, spec/php-spec.coffee
Does exactly what the title says.
`constant.language.class.php` was considered, but constants generally don't change on context, whereas `class` does.
Scope will be more correct.
None.
Fixes #125
=> Tokenize the special 'class' keyword when used in scope resolution

grammars/php.cson, spec/php-spec.coffee
Fixes a faulty word boundary check when declaring `function`s.  Basically, `function_nope` would still be tokenized as a function because we were incorrectly looking for an optional pass-by-reference indicator, itself surrounded by optional whitespace.  There was no required whitespace or word boundary.
None.
Fixes functions.
None.
Fixes #224
=> Functions themselves cannot be passed-by-reference

grammars/php.cson, spec/php-spec.coffee
Support namespaced typehinted variables in function parameters.
None.
See above.
None.
Fixes #222
=> Support namespaced typehints

grammars/php.cson, spec/php-spec.coffee
Adds support for commas at the root level and in function parameters.  Support elsewhere can be trivially added later.
None.
Punctuation improvements.
None.
Fixes #223
=> Add basic support for commas

grammars/php.cson, spec/php-spec.coffee
Mostly a direct copy of language-javascript's `switch_statement` pattern.  Adds new scopes to switch statements and fixes `default:` being recognized as a goto-label.
A less drastic fix would be to create a separate regex for `default:`.
Improved captures, `default:` correctly highlighted (but only inside a switch statement).
The alternative control-style syntax is not affected by these changes.
Fixes #226
=> Add structure to switch statements

grammars/php.cson, spec/php-spec.coffee
Tokenizes PHPDoc [types](https://phpdoc.org/docs/latest/references/phpdoc/types.html).
None.
Fancy highlighting for types in PHPDoc.
Weird highlighting for some themes?
Closes #136
/cc @kroc: could you maybe try this out and report anything weird/broken you encounter?
=> Tokenize PHPDoc param types

grammars/php.cson, spec/php-spec.coffee
I forgot to make the namespace capture repeat, so at most one namespace would be captured.  The capture now repeats and specs have been added (getting rid of a todo, yay!).
An additional minor change adds the `support.other.namespace.php` token to root function calls.
N/A
See above.
None.
Fixes #233
=> Support deeply-namespaced function calls

grammars/php.cson, spec/php-spec.coffee
Basically?  Just adds `\` to the list of acceptable characters.
None.
Adding `\` allows namespaces to be properly tokenized.
None.
Fixes #234
=> Support namespaced PHPDoc types

grammars/php.cson, spec/php-spec.coffee
Splits namespace highlighting into two different rules: one to match the most common `namespace Thing;` syntax, and the other to match the multiline `namespace Thing { /* code */ }` and `namespace { /* code */ }` syntaxes.
Keep the existing rule and just make the identifier optional.
Global namespaces will be tokenized correctly.  Multiline namespaces will also receive the `meta.namespace.php` token, and brackets have their own `punctuation.definition.namespace.begin/end.bracket.curly.php` token.
It is possible that the illegal match I added might …
=> Refactor namespace highlighting

grammars/php.cson, spec/php-spec.coffee
Adds a backup lookahead for the `*/` in case the PHPDoc types are improperly closed.
None.
Comments should always end now.
None.
Fixes #245
=> End PHPDoc even if there are malformed types

grammars/php.cson, spec/php-spec.coffee
This fixes #235. It doesn't make use of `#class-name` as originally suggested, and maybe that would be a slightly better fix, but I couldn't get it to work - https://github.com/atom/language-php/issues/235#issuecomment-318920488. But this works and makes sense.
=> Fix #235 - support \ in use statements

grammars/php.cson
see #247 
The `clone` operator is not a storage type, but instead a keyword, so I moved it out. 
Move it to a different location?
More precise syntax highlighting.
Theme makers may have to restyle it, but most themes just use the `keyword` global scope, so most of them are not affected.
#247
=> move clone operator out of storage.modifier

grammars/php.cson, spec/php-spec.coffee
* Combine the two class `use` patterns into one, because I didn't see that they could be combined before.
* Rename accidental `punctuation.definition.separator.delimiter.php` to `punctuation.separator.delimiter.php`
* Remove what seems to be an unneeded empty-line end match for a different `use` pattern.
None.
* Code cleanup
* Support multiline uses
Minor regressions
Fixes #255
=> Combine class use patterns

grammars/php.cson, spec/php-spec.coffee
These new regexes are taken mostly unmodified from language-javascript.  The only two changes are removing the optional `(o|O)` requirement for octal integers and renaming the period scope to be more inline with other punctuation scopes in language-php.  Other than fixing #260, this PR also fixes a different bug where floats like `.9` would be incorrectly tokenized as the string concatenation operator + the integer `9`.
Fixes #260
=> Improve number regexes

grammars/php.cson, spec/php-spec.coffee
This PR restores the ability to intermingle HTML and PHP at the cost of losing scope context.  In addition, it fixes alternative if/else and switch/case highlighting.
Fixes #236
Fixes #246
Fixes #253
Fixes #273
=> Always end PHP on ?>

grammars/php.cson
Correct the capitalisation of the `__toString` magic method. The other magic methods follow the camelCase convention, so this one should too.
E.g:
=> Correct __toString capitalisation

snippets/language-php.cson
=> Fixed: Block try...catch now uses \Exception instead of Exception

grammars/php.cson, spec/php-spec.coffee
This enhances #278 
It is not specifically mentioned in manual, but the ending semicolon is simply part of end of the statement. There are cases where heredocs will not end with a semicolon:
```php
<?php
foo(<<<END
abcd
END
);
?>
```
=> Allow heredocs to end without a semicolon on the same line

grammars/php.cson
atom/first-mate#100 tweaked first-mate to be more compliant with the original TextMate grammar implementation.  Rules in language-php that were relying on that extra newline have been rewritten to match even if there is no trailing newline.
Alternative first-mate fix.
language-php will work with first-mate@7.0.8+.  This _might_ fix VSCode as well, though I have no idea how I would go about testing that :).
These changes are mostly cosmetic.  The previous end rules were "ensure that there is a next character that is not an identifier", now they're "ensure …
=> Fix issues with TextMate compatibility

grammars/php.cson
Drupal 8 themes use the .theme extension for PHP files. This change adds that as a valid extension.
None considered.
Proper syntax highlighting for .theme files.
None come to mind.
=> Add .theme file extension

grammars/php.cson, spec/php-spec.coffee
Simply uses the `[a-z_\\x{7f}-\\x{ff}\\\\][a-z0-9_\\x{7f}-\\x{ff}\\\\]*` that is commonly found elsewhere throughout language-php.
None.
Namespaces before a scope resolution operator will be tokenized properly.
None.
Fixes #284
Supersedes and closes #281
=> Tokenize namespaces when using the scope resolution operator

grammars/php.cson
The removed pattern matches and tokenizes leading/trailing whitespace for php blocks.  This is rather useless since Atom already does that.  It was also potentially zero-width if it matched at the start of a line, meaning that Atom would break out of the rule, or worse, enter an infinite loop.
Fix the rule.  This was briefly considered and discarded because well, it's redundant.
Removes an unnecessary rule.
None.
Fixes #259
/cc @Ingramz
=> Remove potential zero-width injection pattern

grammars/php.cson, spec/php-spec.coffee
This PR adds scopes for ternaries and the new (as of php7.0) null-coalescing operator.
Currently, this is how the above items are scoped:
```php
// ternary expression
$foo = $bar ? $bar : 'baz';
//            ^text.html.php meta.embedded.block.php source.php
//                   ^text.html.php meta.embedded.block.php source.php
// ternary shorthand
$foo = $bar ?: 'baz';
//            ^^text.html.php meta.embedded.block.php source.php
// null coalescing operator
$foo = $bar ?? 'baz';
//            ^^text.html.php meta.embedded.block.php source.php
```
And here's how it is after the changes I made:
```php
// ternary expression
$foo = $bar ? $bar : 'baz';
//            ^text.html.php meta.embedded.block.php source.php keyword.operator.ternary.php
//                   ^text.html.php …
```
=> Add support for ternary and null coalescing operators

grammars/php.cson, spec/php-spec.coffee
While the PHP manual documents the range of valid identifiers as `[a-z_\x{7f}-\x{ff}][a-z0-9_\x{7f}-\x{ff}]*`, due to a quirk with how PHP parses identifiers it looks at each _byte_ rather than _characters_.  Therefore while `سن` is technically not in that range, its hex representation is `d8 b3 d9 86`, and PHP recognizes it as a valid identifier. To handle this behavior in Atom, we use the modified regex `[a-z_\x{7f}-\x{7fffffff}][a-z0-9_\x{7f}-\x{7fffffff}]*`.  Thanks to @Ingramz for the fix.
Just don't fix this as it's really an odd quirk of PHP. …
=> Handle quirk in how PHP parses identifiers

snippets/language-php.cson
remove unnecessary space at the end of the first line of the `for` snippet
=> remove unnecessary space at the end of line

snippets/language-php.cson
The here doc snippet looks like this:
```php
$var = <<<HTML
content here
;
```
With with a cursor selecting '`HTML`' and a cursor before the semi-colon.
This PR adds '`HTML`' before the semi-colon and selects it. So it initially looks like this:
```php
$var = <<<HTML
content here
HTML;
```
=> fix heredoc snippet

grammars/php.cson, spec/php-spec.coffee
Tokenizes the nullable-type operator `?` per the [RFC](https://wiki.php.net/rfc/nullable_types).
None.
Nullable types will be correctly tokenized both in function parameters and return types.
None.
Fixes #304
=> Tokenize nullable-type operator

grammars/php.cson, spec/php-spec.coffee
What it says on the tin.
Investigating the conflicting interaction with `default:` and goto syntax and getting that fixed as well.  Out of scope, however.
Maybe a different scope for `from` as well, though it feels more correct for `yield from` to have the same scope.
`yield from` generator support.
None.
Fixes #295
=> Tokenize `yield from`

snippets/language-php.cson
PSR (_PHP Standards Recommendations_) recommends that inline comments should use `//` and not `#` :smile: 
Refs: [PSRr](https://github.com/php-fig-rectified/fig-rectified-standards/blob/master/PSR-2-R-coding-style-guide-additions.md#commenting-code) and [PSR](https://www.php-fig.org/psr/psr-2/).
=> Use // instead of # for PHP comments

grammars/html.cson, grammars/php.cson, spec/php-spec.coffee
Now that language-sql has begin/end matches, injections are needed so that the PHP patterns are matched inside the begin/end ones as well.  Unfortunately, due to some annoyances with how injections work, I had to place the injections inside of the wrapper `html.cson` rather than `php.cson`, which would make much more sense.
~~I am also having trouble getting interpolation to work properly.  Seems like it's not picking up source.php correctly, which is discouraging...~~
I would love to hear proposals for alternate designs.
Embedded SQL strings should no …
=> Use injections for SQL strings

grammars/html.cson, grammars/php.cson, spec/php-spec.coffee
language-sql has match patterns for single-line strings that prevent interpolation injections from matching.  To get around this, override those match patterns with our own that recognize interpolations.
Make injections work in matches.  This would get really hairy, really quickly.
Interpolation in single-line strings.
I don't really see any.
Fixes #331
=> Recognize interpolation in SQL strings in embedded SQL

grammars/html.cson, spec/html-spec.coffee
This pull request excludes PHP tag scopes `meta.embedded.block.php` and `meta.embedded.line.php` from injections when PHP code is used within script tags or inline HTML similarly to the base case that does not involve HTML.
N/A
N/A
N/A
Fixes #326
=> Fix PHP tags being injected into PHP source code

grammars/php.cson
As discussed in https://github.com/atom/language-php/issues/351, this rule uses `begin` but it would be less confusing and more consistent with the other rules if it used `match`. This does not change the behavior of the rule.
N/A
Code clarity and consistency
None
https://github.com/atom/language-php/issues/351
=> begin -> match

grammars/php.cson, spec/php-spec.coffee
[The previous pull request](https://github.com/atom/language-php/pull/357) got closed by my mistake as I was trying to force pushing and I couldn't make it open. I'm sorry for that 😞. I'm new to GitHub.
Thanks to @wecc, @Ingramz. It is now ready to be merged.
As already reported in [346](https://github.com/atom/language-php/issues/346) flexible HEREDOC and NOWDOC as introduced in PHP 7.3 will cause syntax highlighting to be failed.
We can have syntax highlighting to be working even if we use flexible HEREDOC and NOWDOC.
The only change which I made was the regex of HEREDOC and NOWDOC endings, so I do not think any particular issue it might cause. As it is most likely how PHP mechanism will detect the end of these two blocks.
So :
```php
$example = foo(
<<<HEREDOC
This is just a cool test. …
```
=> Fixing syntax highlighting issue for flexible HEREDOC and NOWDOC in PHP 7.3

grammars/php.cson, spec/php-spec.coffee
Functions returning references are now correctly colored #343 
Return types are now correctly identified and colored #367 
Return types now are allowed to include namespaces
Test spec for above
Class in return type could be further processed to separate individual parts like namespace, class name. Exactly how function parameters are done, but this is beyond my patience.
Correct colors
I hope none
fix #343 , fix #367 , fix #320
=> Fix functions returning references and return type declarations

grammars/php.cson, spec/php-spec.coffee
It looks like the original author of this section did intend to parse the thing after `instanceof` correctly but only included `a-z` not `A-Za-z`. You can see that this does work as expected with class names starting with a lowercase letter.
Show correct coloring for the class name
I think this is fairly straightforward
atom/language-php#225
microsoft/vscode#88441
=> Parse class with capitol letter after instanceof correctly

grammars/php.cson, spec/html-spec.coffee
Add a positive lookahead regex to allow use of optional semicolon on the `use` operator without breaking the syntax highlighting.
N/A
Allow usage of optional semicolon on the `use` operator
Not that I can think of at the moment.
Resolves https://github.com/atom/language-php/issues/364
=> Fix meta.use end regex

settings/language-php.cson
I have tested this by making a git clone into '/usr/lib/atom/node_modules' and it behaved as intended, with no bugs or warnings.
Changes the default value of of "Non Word Characters" in language-php to match the solution in the thread here:
https://discuss.atom.io/t/double-click-highlights-whole-of-variable-in-php/18625
The thread above suggests (from 2015):
```
$/()"’:,.;<>~!@#%^&*|+=[]{}`?-
```
However, adding a `$` character to the current settings would result in the requested change here, being:
```
$/\()"':,.;<>~!@#%^&*|+=[]{}`?-
```
...This is the new value used in this pull request (2021).
NA: There were no alternatives found because this worked on the first try. Since it was also least invasive, trials went no further.
Double-clicking on a PHP variable is not picked up by …
=> Adding '$' character for highlight-selected

grammars/php.cson, spec/php-spec.coffee
Allow the following syntaxes in phpdoc:
```php
/**
* @param ?int description
*/
```
```php
/**
* @param ?int|?Class description
*/
```
```php
/**
* @param ?int[] description
*/
```
I am not aware of any other alternatives.
Allow the new nullable type syntax.
Not aware of any drawbacks. The change is minor.
That is a step towards solving the need [in this issue](https://github.com/atom/language-php/issues/430).
That is my first pull request to this repo. It's purpose is to be something small that will allow me to learn how to do effective PRs here - learn the rules and pracices, set up the tooling.
My main goal is to ultimately add detection for:
* Psalm complex array types
* PHPStan comments (@phpstan-ignore-line)
* PHPUnit attributes (@test, @dataProvider, etc.)
=> Detect nullable types in phpdoc

grammars/php.cson
This change limits valid characters recognized to 0x10FFFF according to UTF-8 specification.
This is to make the regular expressions PCRE-compliant, where matched characters should not fall out of UTF-8 bounds: https://www.pcre.org/original/doc/html/pcreunicode.html
Since UTF-8 is a standard encoding for PHP files according to [PSR-1](https://www.php-fig.org/psr/psr-1/), I don't see a point supporting any invalid Unicode characters.
The reason for this change is actually to make GitHub Linguist support this grammar as it sticks to strict PCRE rules.
[Before](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fatom%2Flanguage-php%2Fblob%2Fmaster%2Fgrammars%2Fphp.cson&grammar_text=&code_source=from-text&code_url=&co …
=> limit allowed characters to UTF-8 range (0x10FFFF)

grammars/php.cson, spec/php-spec.coffee
Hello,
This tiny PR adds support for [Doctrine Query Language](https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/reference/dql-doctrine-query-language.html) syntax coloration in heredocs.
Example:
Thanks!
=> Add DQL support
